# Generated by Django 5.1.6 on 2025-03-04 07:18

import product_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.BigAutoField(default=product_app.models.generate_product_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('p_name', models.CharField(max_length=255)),
                ('p_description', models.TextField()),
                ('p_quantity', models.IntegerField()),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
