# Generated by Django 5.1.6 on 2025-03-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_fname', models.CharField(max_length=100)),
                ('c_lname', models.CharField(max_length=100)),
                ('c_email', models.EmailField(max_length=100)),
                ('c_phone_number', models.CharField(max_length=20)),
                ('c_city', models.CharField(max_length=50)),
                ('c_state', models.CharField(max_length=50)),
                ('c_country', models.CharField(max_length=50)),
            ],
        ),
    ]
