# Generated by Django 5.1.6 on 2025-03-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_alter_customer_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='c_pincode',
            field=models.CharField(default='0000000', max_length=10),
        ),
    ]
